# Default values for captioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: captioner
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

debug: false
