apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "captioner.fullname" . }}
  labels:
    {{- include "captioner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "captioner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "captioner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: KAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kafka-user-passwords
                key: client-passwords
          {{- if .Values.debug }}
          - name: DEBUG
            value: 1
          {{- end }}
