model_path: ./blip-image-captioning-large
debug: true
topics:
  - to_describe
kafka_config:
  auto_offset_reset: 'earliest'
  bootstrap_servers:
    - 'kafka.default.svc.cluster.local:9092'
  group_id: describer
  security_protocol: SASL_PLAINTEXT
  sasl_mechanism: PLAIN
  sasl_plain_username: user1
