model_path: ./blip-image-captioning-large
debug: true
topics:
  - to_describe
kafka_config:
  auto_offset_reset: 'earliest'
  bootstrap_servers:
    - 'kafka.default.svc.cluster.local:9092'
  consumer_timeout_ms: 1000
  group_id: describer
